curl XPUT http://localhost:10018/riak/travel_pictures/australia1 -H "Content-Type: image/jpeg" -d @australia_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/australia2 -H "Content-Type: image/jpeg" -d @australia_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/hungary1 -H "Content-Type: image/jpeg" -d @hungary_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/hungary2 -H "Content-Type: image/jpeg" -d @hungary_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/mexico1 -H "Content-Type: image/jpeg" -d @mexican_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/mexico2 -H "Content-Type: image/jpeg" -d @mexico_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia1 -H "Content-Type: image/jpeg" -d @slovenia_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia2 -H "Content-Type: image/jpeg" -d @slovenia_city2.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia3 -H "Content-Type: image/jpeg" -d @slovenia_landscape.jpg
