curl XPUT http://localhost:10018/riak/travel_pictures/australia1 -H "Content-Type: image/jpeg" --data-binary @australia_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/australia2 -H "Content-Type: image/jpeg" --data-binary @australia_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/hungary1 -H "Content-Type: image/jpeg" --data-binary @hungary_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/hungary2 -H "Content-Type: image/jpeg" --data-binary @hungary_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/mexico1 -H "Content-Type: image/jpeg" --data-binary @mexican_landscape.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/mexico2 -H "Content-Type: image/jpeg" --data-binary @mexico_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia1 -H "Content-Type: image/jpeg" --data-binary @slovenia_city.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia2 -H "Content-Type: image/jpeg" --data-binary @slovenia_city2.jpg
curl XPUT http://localhost:10018/riak/travel_pictures/slovenia3 -H "Content-Type: image/jpeg" --data-binary @slovenia_landscape.jpg
